MyBotName: MarineTankBot
MyBotRace: Terran
AutoUploadToAiarena: False

UseData: True
Debug: False 
GameStep: 2
DebugGameStep: 2

DebugOptions:
    ActiveGrid: Ground
    ChatDebug: False
    DebugSpawn: False
    ShowPathingCost: False
    ResourceDebug: False

BuildChoices:
    Terran:
        BotName: MarineTankBot
        Cycle:
            - BioTank
        Default: BioTank
        Debug: BioTank
        StrategyUsed: BioTank

Builds:
    BioTank:
        ConstantWorkerProductionTill: 60
        AutoSupplyAtSupply: 18
        OpeningBuildOrder:
            - 14 SupplyDepot
            - 16 Barracks
            - 16 Refinery
            - 19 OrbitalCommand
            - 20 Marine
            - 21 Factory
            - 23 TechLab
            - 25 SiegeTank
